#!/bin/sh

#bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor -d        

bspc config border_width         4
bspc config window_gap          10

bspc config focused_border_color "#00B4DB" # focused window
bspc config normal_border_color "#0F2027" # unfocused window

"" MASTER AND STACK LAYOUT 
bspc config initial_polarity first_child
      
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
bsp-layout set tall  -- --master-size 0.5
""

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a qBittorrent desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
