#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          20

"" MASTER AND STACK LAYOUT 
bspc config initial_polarity first_child
bsp-layout set tall I -- --master-size 0.5
bsp-layout set tall II -- --master-size 0.5
bsp-layout set tall III -- --master-size 0.5
bsp-layout set tall IV -- --master-size 0.5
bsp-layout set tall V -- --master-size 0.5
bsp-layout set tall VI -- --master-size 0.5
bsp-layout set tall VII -- --master-size 0.5
bsp-layout set tall VIII -- --master-size 0.5
bsp-layout set tall IX -- --master-size 0.5
bsp-layout set tall X -- --master-size 0.5
""

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

"bspc rule -a Gimp desktop='^3' state=floating follow=on "
bspc rule -a discord desktop='^3'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Screenkey manage=off
